# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/seokjun/kubig2025

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/seokjun/kubig2025

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seokjun/kubig2025/CMakeFiles /home/seokjun/kubig2025//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seokjun/kubig2025/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bookSql

# Build rule for target.
bookSql: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bookSql
.PHONY : bookSql

# fast build rule for target.
bookSql/fast:
	$(MAKE) $(MAKESILENT) -f sqlQuery/CMakeFiles/bookSql.dir/build.make sqlQuery/CMakeFiles/bookSql.dir/build
.PHONY : bookSql/fast

#=============================================================================
# Target rules for targets named arithmetics

# Build rule for target.
arithmetics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arithmetics
.PHONY : arithmetics

# fast build rule for target.
arithmetics/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part1/CMakeFiles/arithmetics.dir/build.make c_example/part1/CMakeFiles/arithmetics.dir/build
.PHONY : arithmetics/fast

#=============================================================================
# Target rules for targets named celsius

# Build rule for target.
celsius: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 celsius
.PHONY : celsius

# fast build rule for target.
celsius/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part1/CMakeFiles/celsius.dir/build.make c_example/part1/CMakeFiles/celsius.dir/build
.PHONY : celsius/fast

#=============================================================================
# Target rules for targets named charnumber

# Build rule for target.
charnumber: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 charnumber
.PHONY : charnumber

# fast build rule for target.
charnumber/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part1/CMakeFiles/charnumber.dir/build.make c_example/part1/CMakeFiles/charnumber.dir/build
.PHONY : charnumber/fast

#=============================================================================
# Target rules for targets named compare

# Build rule for target.
compare: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compare
.PHONY : compare

# fast build rule for target.
compare/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part1/CMakeFiles/compare.dir/build.make c_example/part1/CMakeFiles/compare.dir/build
.PHONY : compare/fast

#=============================================================================
# Target rules for targets named compare2

# Build rule for target.
compare2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compare2
.PHONY : compare2

# fast build rule for target.
compare2/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part1/CMakeFiles/compare2.dir/build.make c_example/part1/CMakeFiles/compare2.dir/build
.PHONY : compare2/fast

#=============================================================================
# Target rules for targets named ddd

# Build rule for target.
ddd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ddd
.PHONY : ddd

# fast build rule for target.
ddd/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part1/CMakeFiles/ddd.dir/build.make c_example/part1/CMakeFiles/ddd.dir/build
.PHONY : ddd/fast

#=============================================================================
# Target rules for targets named free

# Build rule for target.
free: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 free
.PHONY : free

# fast build rule for target.
free/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part1/CMakeFiles/free.dir/build.make c_example/part1/CMakeFiles/free.dir/build
.PHONY : free/fast

#=============================================================================
# Target rules for targets named gender

# Build rule for target.
gender: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gender
.PHONY : gender

# fast build rule for target.
gender/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part1/CMakeFiles/gender.dir/build.make c_example/part1/CMakeFiles/gender.dir/build
.PHONY : gender/fast

#=============================================================================
# Target rules for targets named increase

# Build rule for target.
increase: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 increase
.PHONY : increase

# fast build rule for target.
increase/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part1/CMakeFiles/increase.dir/build.make c_example/part1/CMakeFiles/increase.dir/build
.PHONY : increase/fast

#=============================================================================
# Target rules for targets named infinit

# Build rule for target.
infinit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 infinit
.PHONY : infinit

# fast build rule for target.
infinit/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part1/CMakeFiles/infinit.dir/build.make c_example/part1/CMakeFiles/infinit.dir/build
.PHONY : infinit/fast

#=============================================================================
# Target rules for targets named limit

# Build rule for target.
limit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 limit
.PHONY : limit

# fast build rule for target.
limit/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part1/CMakeFiles/limit.dir/build.make c_example/part1/CMakeFiles/limit.dir/build
.PHONY : limit/fast

#=============================================================================
# Target rules for targets named literal

# Build rule for target.
literal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 literal
.PHONY : literal

# fast build rule for target.
literal/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part1/CMakeFiles/literal.dir/build.make c_example/part1/CMakeFiles/literal.dir/build
.PHONY : literal/fast

#=============================================================================
# Target rules for targets named oddeven

# Build rule for target.
oddeven: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 oddeven
.PHONY : oddeven

# fast build rule for target.
oddeven/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part1/CMakeFiles/oddeven.dir/build.make c_example/part1/CMakeFiles/oddeven.dir/build
.PHONY : oddeven/fast

#=============================================================================
# Target rules for targets named sizeof

# Build rule for target.
sizeof: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sizeof
.PHONY : sizeof

# fast build rule for target.
sizeof/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part1/CMakeFiles/sizeof.dir/build.make c_example/part1/CMakeFiles/sizeof.dir/build
.PHONY : sizeof/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part1/CMakeFiles/test.dir/build.make c_example/part1/CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named triangle

# Build rule for target.
triangle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 triangle
.PHONY : triangle

# fast build rule for target.
triangle/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part1/CMakeFiles/triangle.dir/build.make c_example/part1/CMakeFiles/triangle.dir/build
.PHONY : triangle/fast

#=============================================================================
# Target rules for targets named triangle2

# Build rule for target.
triangle2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 triangle2
.PHONY : triangle2

# fast build rule for target.
triangle2/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part1/CMakeFiles/triangle2.dir/build.make c_example/part1/CMakeFiles/triangle2.dir/build
.PHONY : triangle2/fast

#=============================================================================
# Target rules for targets named 1to10

# Build rule for target.
1to10: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 1to10
.PHONY : 1to10

# fast build rule for target.
1to10/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/1to10.dir/build.make c_example/part2/CMakeFiles/1to10.dir/build
.PHONY : 1to10/fast

#=============================================================================
# Target rules for targets named 1to10000

# Build rule for target.
1to10000: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 1to10000
.PHONY : 1to10000

# fast build rule for target.
1to10000/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/1to10000.dir/build.make c_example/part2/CMakeFiles/1to10000.dir/build
.PHONY : 1to10000/fast

#=============================================================================
# Target rules for targets named 2022avgtemp

# Build rule for target.
2022avgtemp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 2022avgtemp
.PHONY : 2022avgtemp

# fast build rule for target.
2022avgtemp/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/2022avgtemp.dir/build.make c_example/part2/CMakeFiles/2022avgtemp.dir/build
.PHONY : 2022avgtemp/fast

#=============================================================================
# Target rules for targets named PosZeroNeg

# Build rule for target.
PosZeroNeg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PosZeroNeg
.PHONY : PosZeroNeg

# fast build rule for target.
PosZeroNeg/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/PosZeroNeg.dir/build.make c_example/part2/CMakeFiles/PosZeroNeg.dir/build
.PHONY : PosZeroNeg/fast

#=============================================================================
# Target rules for targets named absolute

# Build rule for target.
absolute: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 absolute
.PHONY : absolute

# fast build rule for target.
absolute/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/absolute.dir/build.make c_example/part2/CMakeFiles/absolute.dir/build
.PHONY : absolute/fast

#=============================================================================
# Target rules for targets named ascil

# Build rule for target.
ascil: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ascil
.PHONY : ascil

# fast build rule for target.
ascil/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/ascil.dir/build.make c_example/part2/CMakeFiles/ascil.dir/build
.PHONY : ascil/fast

#=============================================================================
# Target rules for targets named baseball

# Build rule for target.
baseball: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 baseball
.PHONY : baseball

# fast build rule for target.
baseball/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/baseball.dir/build.make c_example/part2/CMakeFiles/baseball.dir/build
.PHONY : baseball/fast

#=============================================================================
# Target rules for targets named bigletter

# Build rule for target.
bigletter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bigletter
.PHONY : bigletter

# fast build rule for target.
bigletter/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/bigletter.dir/build.make c_example/part2/CMakeFiles/bigletter.dir/build
.PHONY : bigletter/fast

#=============================================================================
# Target rules for targets named dice

# Build rule for target.
dice: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dice
.PHONY : dice

# fast build rule for target.
dice/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/dice.dir/build.make c_example/part2/CMakeFiles/dice.dir/build
.PHONY : dice/fast

#=============================================================================
# Target rules for targets named findarray

# Build rule for target.
findarray: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 findarray
.PHONY : findarray

# fast build rule for target.
findarray/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/findarray.dir/build.make c_example/part2/CMakeFiles/findarray.dir/build
.PHONY : findarray/fast

#=============================================================================
# Target rules for targets named findmax

# Build rule for target.
findmax: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 findmax
.PHONY : findmax

# fast build rule for target.
findmax/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/findmax.dir/build.make c_example/part2/CMakeFiles/findmax.dir/build
.PHONY : findmax/fast

#=============================================================================
# Target rules for targets named function

# Build rule for target.
function: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 function
.PHONY : function

# fast build rule for target.
function/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/function.dir/build.make c_example/part2/CMakeFiles/function.dir/build
.PHONY : function/fast

#=============================================================================
# Target rules for targets named grade

# Build rule for target.
grade: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grade
.PHONY : grade

# fast build rule for target.
grade/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/grade.dir/build.make c_example/part2/CMakeFiles/grade.dir/build
.PHONY : grade/fast

#=============================================================================
# Target rules for targets named grade2

# Build rule for target.
grade2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 grade2
.PHONY : grade2

# fast build rule for target.
grade2/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/grade2.dir/build.make c_example/part2/CMakeFiles/grade2.dir/build
.PHONY : grade2/fast

#=============================================================================
# Target rules for targets named leafyear

# Build rule for target.
leafyear: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 leafyear
.PHONY : leafyear

# fast build rule for target.
leafyear/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/leafyear.dir/build.make c_example/part2/CMakeFiles/leafyear.dir/build
.PHONY : leafyear/fast

#=============================================================================
# Target rules for targets named multiply

# Build rule for target.
multiply: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 multiply
.PHONY : multiply

# fast build rule for target.
multiply/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/multiply.dir/build.make c_example/part2/CMakeFiles/multiply.dir/build
.PHONY : multiply/fast

#=============================================================================
# Target rules for targets named one2ten

# Build rule for target.
one2ten: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 one2ten
.PHONY : one2ten

# fast build rule for target.
one2ten/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/one2ten.dir/build.make c_example/part2/CMakeFiles/one2ten.dir/build
.PHONY : one2ten/fast

#=============================================================================
# Target rules for targets named passfail

# Build rule for target.
passfail: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 passfail
.PHONY : passfail

# fast build rule for target.
passfail/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/passfail.dir/build.make c_example/part2/CMakeFiles/passfail.dir/build
.PHONY : passfail/fast

#=============================================================================
# Target rules for targets named power

# Build rule for target.
power: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 power
.PHONY : power

# fast build rule for target.
power/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/power.dir/build.make c_example/part2/CMakeFiles/power.dir/build
.PHONY : power/fast

#=============================================================================
# Target rules for targets named proscore

# Build rule for target.
proscore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 proscore
.PHONY : proscore

# fast build rule for target.
proscore/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/proscore.dir/build.make c_example/part2/CMakeFiles/proscore.dir/build
.PHONY : proscore/fast

#=============================================================================
# Target rules for targets named random

# Build rule for target.
random: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 random
.PHONY : random

# fast build rule for target.
random/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/random.dir/build.make c_example/part2/CMakeFiles/random.dir/build
.PHONY : random/fast

#=============================================================================
# Target rules for targets named return

# Build rule for target.
return: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 return
.PHONY : return

# fast build rule for target.
return/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/return.dir/build.make c_example/part2/CMakeFiles/return.dir/build
.PHONY : return/fast

#=============================================================================
# Target rules for targets named scoregrade

# Build rule for target.
scoregrade: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 scoregrade
.PHONY : scoregrade

# fast build rule for target.
scoregrade/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/scoregrade.dir/build.make c_example/part2/CMakeFiles/scoregrade.dir/build
.PHONY : scoregrade/fast

#=============================================================================
# Target rules for targets named star

# Build rule for target.
star: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 star
.PHONY : star

# fast build rule for target.
star/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/star.dir/build.make c_example/part2/CMakeFiles/star.dir/build
.PHONY : star/fast

#=============================================================================
# Target rules for targets named static

# Build rule for target.
static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 static
.PHONY : static

# fast build rule for target.
static/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/static.dir/build.make c_example/part2/CMakeFiles/static.dir/build
.PHONY : static/fast

#=============================================================================
# Target rules for targets named sumMatrix

# Build rule for target.
sumMatrix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sumMatrix
.PHONY : sumMatrix

# fast build rule for target.
sumMatrix/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/sumMatrix.dir/build.make c_example/part2/CMakeFiles/sumMatrix.dir/build
.PHONY : sumMatrix/fast

#=============================================================================
# Target rules for targets named sumarray

# Build rule for target.
sumarray: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sumarray
.PHONY : sumarray

# fast build rule for target.
sumarray/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/sumarray.dir/build.make c_example/part2/CMakeFiles/sumarray.dir/build
.PHONY : sumarray/fast

#=============================================================================
# Target rules for targets named test1

# Build rule for target.
test1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test1
.PHONY : test1

# fast build rule for target.
test1/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part2/CMakeFiles/test1.dir/build.make c_example/part2/CMakeFiles/test1.dir/build
.PHONY : test1/fast

#=============================================================================
# Target rules for targets named arrayassignment

# Build rule for target.
arrayassignment: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arrayassignment
.PHONY : arrayassignment

# fast build rule for target.
arrayassignment/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/arrayassignment.dir/build.make c_example/part3/CMakeFiles/arrayassignment.dir/build
.PHONY : arrayassignment/fast

#=============================================================================
# Target rules for targets named arraycompare

# Build rule for target.
arraycompare: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arraycompare
.PHONY : arraycompare

# fast build rule for target.
arraycompare/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/arraycompare.dir/build.make c_example/part3/CMakeFiles/arraycompare.dir/build
.PHONY : arraycompare/fast

#=============================================================================
# Target rules for targets named arraypointer

# Build rule for target.
arraypointer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 arraypointer
.PHONY : arraypointer

# fast build rule for target.
arraypointer/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/arraypointer.dir/build.make c_example/part3/CMakeFiles/arraypointer.dir/build
.PHONY : arraypointer/fast

#=============================================================================
# Target rules for targets named bubble

# Build rule for target.
bubble: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bubble
.PHONY : bubble

# fast build rule for target.
bubble/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/bubble.dir/build.make c_example/part3/CMakeFiles/bubble.dir/build
.PHONY : bubble/fast

#=============================================================================
# Target rules for targets named charAdress

# Build rule for target.
charAdress: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 charAdress
.PHONY : charAdress

# fast build rule for target.
charAdress/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/charAdress.dir/build.make c_example/part3/CMakeFiles/charAdress.dir/build
.PHONY : charAdress/fast

#=============================================================================
# Target rules for targets named charPointerOperation

# Build rule for target.
charPointerOperation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 charPointerOperation
.PHONY : charPointerOperation

# fast build rule for target.
charPointerOperation/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/charPointerOperation.dir/build.make c_example/part3/CMakeFiles/charPointerOperation.dir/build
.PHONY : charPointerOperation/fast

#=============================================================================
# Target rules for targets named dynamic

# Build rule for target.
dynamic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dynamic
.PHONY : dynamic

# fast build rule for target.
dynamic/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/dynamic.dir/build.make c_example/part3/CMakeFiles/dynamic.dir/build
.PHONY : dynamic/fast

#=============================================================================
# Target rules for targets named endian

# Build rule for target.
endian: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 endian
.PHONY : endian

# fast build rule for target.
endian/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/endian.dir/build.make c_example/part3/CMakeFiles/endian.dir/build
.PHONY : endian/fast

#=============================================================================
# Target rules for targets named enumExaple

# Build rule for target.
enumExaple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 enumExaple
.PHONY : enumExaple

# fast build rule for target.
enumExaple/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/enumExaple.dir/build.make c_example/part3/CMakeFiles/enumExaple.dir/build
.PHONY : enumExaple/fast

#=============================================================================
# Target rules for targets named fileDescripor

# Build rule for target.
fileDescripor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fileDescripor
.PHONY : fileDescripor

# fast build rule for target.
fileDescripor/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/fileDescripor.dir/build.make c_example/part3/CMakeFiles/fileDescripor.dir/build
.PHONY : fileDescripor/fast

#=============================================================================
# Target rules for targets named filePointer

# Build rule for target.
filePointer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 filePointer
.PHONY : filePointer

# fast build rule for target.
filePointer/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/filePointer.dir/build.make c_example/part3/CMakeFiles/filePointer.dir/build
.PHONY : filePointer/fast

#=============================================================================
# Target rules for targets named function1

# Build rule for target.
function1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 function1
.PHONY : function1

# fast build rule for target.
function1/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/function1.dir/build.make c_example/part3/CMakeFiles/function1.dir/build
.PHONY : function1/fast

#=============================================================================
# Target rules for targets named getSeries

# Build rule for target.
getSeries: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 getSeries
.PHONY : getSeries

# fast build rule for target.
getSeries/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/getSeries.dir/build.make c_example/part3/CMakeFiles/getSeries.dir/build
.PHONY : getSeries/fast

#=============================================================================
# Target rules for targets named helloString

# Build rule for target.
helloString: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 helloString
.PHONY : helloString

# fast build rule for target.
helloString/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/helloString.dir/build.make c_example/part3/CMakeFiles/helloString.dir/build
.PHONY : helloString/fast

#=============================================================================
# Target rules for targets named pointer

# Build rule for target.
pointer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pointer
.PHONY : pointer

# fast build rule for target.
pointer/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/pointer.dir/build.make c_example/part3/CMakeFiles/pointer.dir/build
.PHONY : pointer/fast

#=============================================================================
# Target rules for targets named pointer2

# Build rule for target.
pointer2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pointer2
.PHONY : pointer2

# fast build rule for target.
pointer2/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/pointer2.dir/build.make c_example/part3/CMakeFiles/pointer2.dir/build
.PHONY : pointer2/fast

#=============================================================================
# Target rules for targets named qsort

# Build rule for target.
qsort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qsort
.PHONY : qsort

# fast build rule for target.
qsort/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/qsort.dir/build.make c_example/part3/CMakeFiles/qsort.dir/build
.PHONY : qsort/fast

#=============================================================================
# Target rules for targets named selection

# Build rule for target.
selection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 selection
.PHONY : selection

# fast build rule for target.
selection/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/selection.dir/build.make c_example/part3/CMakeFiles/selection.dir/build
.PHONY : selection/fast

#=============================================================================
# Target rules for targets named strcatExample

# Build rule for target.
strcatExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 strcatExample
.PHONY : strcatExample

# fast build rule for target.
strcatExample/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/strcatExample.dir/build.make c_example/part3/CMakeFiles/strcatExample.dir/build
.PHONY : strcatExample/fast

#=============================================================================
# Target rules for targets named sumarrayfunction

# Build rule for target.
sumarrayfunction: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sumarrayfunction
.PHONY : sumarrayfunction

# fast build rule for target.
sumarrayfunction/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/sumarrayfunction.dir/build.make c_example/part3/CMakeFiles/sumarrayfunction.dir/build
.PHONY : sumarrayfunction/fast

#=============================================================================
# Target rules for targets named summatrix

# Build rule for target.
summatrix: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 summatrix
.PHONY : summatrix

# fast build rule for target.
summatrix/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/summatrix.dir/build.make c_example/part3/CMakeFiles/summatrix.dir/build
.PHONY : summatrix/fast

#=============================================================================
# Target rules for targets named summatrix2

# Build rule for target.
summatrix2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 summatrix2
.PHONY : summatrix2

# fast build rule for target.
summatrix2/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/summatrix2.dir/build.make c_example/part3/CMakeFiles/summatrix2.dir/build
.PHONY : summatrix2/fast

#=============================================================================
# Target rules for targets named swap

# Build rule for target.
swap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 swap
.PHONY : swap

# fast build rule for target.
swap/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/swap.dir/build.make c_example/part3/CMakeFiles/swap.dir/build
.PHONY : swap/fast

#=============================================================================
# Target rules for targets named swapfunction

# Build rule for target.
swapfunction: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 swapfunction
.PHONY : swapfunction

# fast build rule for target.
swapfunction/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/swapfunction.dir/build.make c_example/part3/CMakeFiles/swapfunction.dir/build
.PHONY : swapfunction/fast

#=============================================================================
# Target rules for targets named unionExample

# Build rule for target.
unionExample: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unionExample
.PHONY : unionExample

# fast build rule for target.
unionExample/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/unionExample.dir/build.make c_example/part3/CMakeFiles/unionExample.dir/build
.PHONY : unionExample/fast

#=============================================================================
# Target rules for targets named void

# Build rule for target.
void: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 void
.PHONY : void

# fast build rule for target.
void/fast:
	$(MAKE) $(MAKESILENT) -f c_example/part3/CMakeFiles/void.dir/build.make c_example/part3/CMakeFiles/void.dir/build
.PHONY : void/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 1to10"
	@echo "... 1to10000"
	@echo "... 2022avgtemp"
	@echo "... PosZeroNeg"
	@echo "... absolute"
	@echo "... arithmetics"
	@echo "... arrayassignment"
	@echo "... arraycompare"
	@echo "... arraypointer"
	@echo "... ascil"
	@echo "... baseball"
	@echo "... bigletter"
	@echo "... bookSql"
	@echo "... bubble"
	@echo "... celsius"
	@echo "... charAdress"
	@echo "... charPointerOperation"
	@echo "... charnumber"
	@echo "... compare"
	@echo "... compare2"
	@echo "... ddd"
	@echo "... dice"
	@echo "... dynamic"
	@echo "... endian"
	@echo "... enumExaple"
	@echo "... fileDescripor"
	@echo "... filePointer"
	@echo "... findarray"
	@echo "... findmax"
	@echo "... free"
	@echo "... function"
	@echo "... function1"
	@echo "... gender"
	@echo "... getSeries"
	@echo "... grade"
	@echo "... grade2"
	@echo "... helloString"
	@echo "... increase"
	@echo "... infinit"
	@echo "... leafyear"
	@echo "... limit"
	@echo "... literal"
	@echo "... multiply"
	@echo "... oddeven"
	@echo "... one2ten"
	@echo "... passfail"
	@echo "... pointer"
	@echo "... pointer2"
	@echo "... power"
	@echo "... proscore"
	@echo "... qsort"
	@echo "... random"
	@echo "... return"
	@echo "... scoregrade"
	@echo "... selection"
	@echo "... sizeof"
	@echo "... star"
	@echo "... static"
	@echo "... strcatExample"
	@echo "... sumMatrix"
	@echo "... sumarray"
	@echo "... sumarrayfunction"
	@echo "... summatrix"
	@echo "... summatrix2"
	@echo "... swap"
	@echo "... swapfunction"
	@echo "... test"
	@echo "... test1"
	@echo "... triangle"
	@echo "... triangle2"
	@echo "... unionExample"
	@echo "... void"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

