TARGET = swap selection bubble pointer endian point2 function void arraypointer arrayassignment arraycompare swapfunction sumarrayfunction summatrix summatrix2 helloString charPointerOperation strcatExample filePointer fileDescripor dynamic charAdress unionExample enumExaple

all : ${TARGET}

swap: $@
selection: $@
bubble : $@
pointer: $@
endian: $@
point2 : $@
function :$@
void : $@
arraypointer :$@
arrayassignment :$@
arraycompare :$@
swapfunction: $@
sumarrayfunction :$@
summatrix :$@
summatrix2:$@
helloString:$@
charPointerOperation: $@
strcatExample: $@
filePointer :$@
fileDescripor:$@
dynamic :$@
charAdress :$@
unionExample :$@
enumExaple :$@

clean :
	rm ${TARGET}
	