TARGET = swap selection bubble pointer endian point2 function void arraypointer arrayassignment arraycompare swapfunction sumarrayfunction summatrix summatrix2

all : ${TARGET}

swap: $@
selection: $@
bubble : $@
pointer: $@
endian: $@
point2 : $@
function :$@
void : $@
arraypointer :$@
arrayassignment :$@
arraycompare :$@
swapfunction: $@
sumarrayfunction :$@
summatrix :$@
summatrix2:$@

clean :
	rm ${TARGET}
	