TARGET = infinit celsius charnumber test ddd triangle triangle2 arithmetics increase literal


all : ${TARGET}


infinit : $@

free : $@
celsius : $@
charnumber : $@
test : $@
ddd: $@
triangle : $@
riangle2 :$@
arithmetics : $@
increase : $@
literal :$@

clean :
	rm ${TARGET}