TARGET = infinit celsius charnumber test ddd triangle triangle2 arithmetics increase literal limit gender compare compare2 sizeof oddeven fourbit fourbit2
 

all : ${TARGET}

oddeven :$@
infinit : $@
sizeof : $@
free : $@
celsius : $@
charnumber : $@
test : $@
ddd: $@
triangle : $@
riangle2 :$@
arithmetics : $@
increase : $@
literal :$@
limit: $@
gnder : $@
compare : $@
compare2: $@
fourbit: $@
fourbit2: $@


clean :
	rm ${TARGET}