TARGET = absolute leafyear passfail grade grade2 PosZeroNeg bigletter one2ten 1to10000 multiply ascil star
all : ${TARGET}

one2ten : $@
absolute :$@
PosZeroNeg :$@
leafyear :$@
passfail :$@
grade :$@
grade2 :$@
bigletter :$@
1to10000: $@
multiply: $@
ascil: $@
star: $@
clean :
	rm ${TARGET}
	