TARGET = absolute leafyear passfail grade grade2 PosZeroNeg bigletter one2ten 1to10000 multiply ascil star 1to10 random static function return power test dice sumarray sumMatrix findmax findarray scoregrade proscore 2022avgtemp baseball test
all : ${TARGET}

return : $@
one2ten : $@
absolute :$@
PosZeroNeg :$@
leafyear :$@
passfail :$@
grade :$@
grade2 :$@
bigletter :$@
1to10000: $@
multiply: $@
ascil: $@
star: $@
1to10: $@
random:$@
static:$@
function :$@
power : $@
test:$@
dice:$@
sumarray :$@
sumMatrix:$@
findmax:$@
findarray:$@
scoregrade :$@
proscore:$@
2022avgtemp:$@
baseball :$@
test:$@
clean :
	rm ${TARGET}
	